In [1]:
import datetime
import os
from glob import glob
import netCDF4 as nc
import numpy as np
import pandas as pd

### Load data

In [2]:
data_path = 'ME4OH_EN411_OFAM3/data/en4.1.1/1993-2014/'
files = [f for f in glob(os.path.join(data_path, "*.nc"))]

In [20]:
def load_and_filter_ohc(filepath):
    """Load data file, extract variables, filter for layer 1 OHC"""
    file_data = nc.Dataset(filepath,'r')

    # Extract variables
    lat = file_data["ts_lat"][:].data  # Latitude
    long = file_data["ts_lon"][:].data  # Longitude
    time = file_data["en4_ymd"][:].data  # Year , month , day
    mask = file_data["dohc_mask_by_en4_maxdepth"][:].data # Valid profile mask
    dohc1 = file_data["dohc"][:, 0].data  # Layer 1 OHC anomaly target (NOTE: index 0 in python, index 1 in R)
    ssh = file_data["eta_t"][:].data  # Sea surface height

    # Filter to valid OHC
    # Only valid Layer-1 profiles included according to mask and remove NaNs
    idx = [i for i in range(len(mask)) if mask[i, 0] == 1]
    filtered_dohc1 = np.array([dohc1[i] for i in idx])
    filtered_lat = np.array([lat[i] for i in idx])
    filtered_long = np.array([long[i] for i in idx])
    filtered_date = np.array([datetime.date(int(time[i, 0]), int(time[i, 1]), int(time[i, 2])) for i in idx])
    filtered_ssh = np.array([ssh[i] for i in idx])

    # Make df
    ohc_df = pd.DataFrame({
        "Date": filtered_date,
        "Latitude": filtered_lat,
        "Longitude": filtered_long,
        "OHC": filtered_dohc1,
        "SSH": filtered_ssh
    })
    ohc_df = ohc_df.dropna()
    
    return ohc_df

In [7]:
# Temporarily filter to only 10 files
files = files[0:10]

In [21]:
ohc_df = load_and_filter_ohc(files[0])
for path in files[1:]:
    file_df = load_and_filter_ohc(path)
    ohc_df = pd.concat([ohc_df, file_df])

ohc_df

            Date   Latitude   Longitude       OHC       SSH
0     1993-09-12 -65.050003  236.649994  0.343876 -1.691031
1     1993-09-10 -64.050003  221.550003  0.344592 -1.746879
2     1993-09-15 -63.549999  244.350006  0.345307 -1.345561
3     1993-09-11 -63.349998  278.549988  0.345918 -1.107517
4     1993-09-12 -62.849998  219.149994  0.344311 -1.786248
...          ...        ...         ...       ...       ...
7482  1993-02-13  74.550003    6.050000  0.345806 -0.796838
7487  1993-02-18  74.550003   30.350000  0.345589 -0.713523
7488  1993-02-14  74.750000    3.350000  0.345679 -0.827662
7489  1993-02-17  74.750000  359.049988  0.344764 -0.812708
7490  1993-02-17  74.750000  359.850006  0.345423 -0.834681

[116158 rows x 5 columns]

In [ ]:
ohc_df = pd.DataFrame({
    "Date": all_date,
    "Latitude": all_lat,
    "Longitude": all_long,
    "OHC": all_dohc1,
    "SSH": all_ssh
})
ohc_df = ohc_df.dropna()
ohc_df

              Date   Latitude   Longitude       OHC       SSH
0       1993-09-12 -65.050003  236.649994  0.343876 -1.691031
1       1993-09-10 -64.050003  221.550003  0.344592 -1.746879
2       1993-09-15 -63.549999  244.350006  0.345307 -1.345561
3       1993-09-11 -63.349998  278.549988  0.345918 -1.107517
4       1993-09-12 -62.849998  219.149994  0.344311 -1.786248
...            ...        ...         ...       ...       ...
117583  1993-02-13  74.550003    6.050000  0.345806 -0.796838
117588  1993-02-18  74.550003   30.350000  0.345589 -0.713523
117589  1993-02-14  74.750000    3.350000  0.345679 -0.827662
117590  1993-02-17  74.750000  359.049988  0.344764 -0.812708
117591  1993-02-17  74.750000  359.850006  0.345423 -0.834681

[116158 rows x 5 columns]

In [11]:
filepath = 'ME4OH_EN411_OFAM3/data/en4.1.1/1993-2014/ofam3-jra55.all.EN.4.1.1.f.profiles.g10.199301.update.extra.anom.199301_201412.nc'
file2read = nc.Dataset(filepath,'r')
print(file2read.variables.keys())

dict_keys(['en4_lat', 'en4_lon', 'en4_ymd', 'en4_ydec', 'en4_maxdepth', 'en4_wmo_inst_type', 'en4_project_name', 'en4_platform_number', 'en4_instrument_type', 'en4_inst_reference', 'en4_data_centre', 'ts_lat', 'ts_lon', 'ts_z', 'ts_dz', 'ts_bound', 'eta_t', 'sst', 'dohc', 'adohc', 'dohc_mask_by_en4_maxdepth', 'temp', 'salt'])

In [12]:
lat = file2read["ts_lat"][:].data  # Latitude
long = file2read["ts_lon"][:].data  # Longitude
time = file2read["en4_ymd"][:].data  # Year , month , day
mask = file2read["dohc_mask_by_en4_maxdepth"][:].data # Valid profile mask
dohc1 = file2read["dohc"][:, 0].data  # Layer 1 OHC anomaly target (NOTE: index 0 in python, index 1 in R)
ssh = file2read["eta_t"][:].data  # Sea surface height
# salt = file2read["salt"][:].data  # Salinity

### Filter data
To valid Layer-1 profiles according to mask and remove NaNs

In [13]:
idx = [i for i in range(len(mask)) if mask[i, 0] == 1]
filtered_dohc1 = np.array([dohc1[i] for i in idx])
filtered_lat = np.array([lat[i] for i in idx])
filtered_long = np.array([long[i] for i in idx])
filtered_date = np.array([datetime.date(int(time[i, 0]), int(time[i, 1]), int(time[i, 2])) for i in idx])
filtered_ssh = np.array([ssh[i] for i in idx])

In [ ]:
ohc_df = pd.DataFrame({
    "Date": filtered_date,
    "Latitude": filtered_lat,
    "Longitude": filtered_long,
    "OHC": filtered_dohc1,
    "SSH": filtered_ssh
})
ohc_df = ohc_df.dropna()
ohc_df

            Date   Latitude   Longitude       OHC
0     1993-01-18 -69.250000  271.950012  0.344897
1     1993-01-27 -68.949997  290.149994  0.344191
2     1993-01-27 -68.949997  290.450012  0.344145
3     1993-01-14 -68.949997  301.049988  0.342160
4     1993-01-15 -68.949997  302.049988  0.342066
...          ...        ...         ...       ...
6782  1993-01-25  73.849998   31.250000  0.347506
6783  1993-01-18  74.050003   23.049999  0.347372
6784  1993-01-19  74.050003   25.049999  0.348112
6785  1993-01-24  74.050003   27.049999  0.347161
6786  1993-01-24  74.050003   29.049999  0.347562

[6662 rows x 4 columns]

In [14]:
filtered_date

array([datetime.date(1993, 1, 18), datetime.date(1993, 1, 27),
       datetime.date(1993, 1, 27), ..., datetime.date(1993, 1, 24),
       datetime.date(1993, 1, 21), datetime.date(1993, 1, 21)],
      shape=(6789,), dtype=object)

# EDA

- Amount of data points across time
- Amount of data across space
- Plot OHC vs lat long for a single month?